### ISSUE TITLE
ping cheerio to 1.0.0-rc.12

### ISSUE THREAD

**Issue by adrai** [kawanet/rdotjson#13]
@kawanet can we ping the version of cheerio to 1.0.0-rc.12 and release a new patch version?
Seems with v1.0.0 they dropped some older Node.js versions

https://github.com/kawanet/rdotjson/blob/master/package.json#L17C17

```diff
-"cheerio": "^1.0.0-rc.12",
+"cheerio": "1.0.0-rc.12",
```

this may help for: https://github.com/locize/locize-cli/issues/95

**Comment by kawanet** [comment]
Thanks! It looks cheerio has the 1.0.0 major version (not RC) just released 4 days ago.

https://www.npmjs.com/package/cheerio?activeTab=versions

Node.js v16 has already got its [EOL](https://github.com/nodejs/Release) at 2023-09-11.
It sounds fair to drop v16 support though, as you mentioned at the issue there.

https://github.com/cheeriojs/cheerio/blob/v1.0.0-rc.12/package.json

```json
  "engines": {
    "node": ">= 6"
  },
```

https://github.com/cheeriojs/cheerio/blob/v1.0.0/package.json

```json
  "engines": {
    "node": ">=18.17"
  },
```

**Comment by adrai** [comment]
Best would be if we could create 2 releases. 1 patch release (fixing cheerio) and 1 major release (bumping node and using the new cheerio version).
Is that ok for you?

**Comment by kawanet** [comment]
Thanks, @adrai !

| rdotjson | node.js | cheerio | status |
|---|---|---|---|
| `1.1.0` | no requirement | `^1.0.0-rc.12` | published at 2023 |
| `1.1.1` | no requirement | `1.0.0-rc.12` fixed | will be published soon |
| `2.0.0` | `"node": ">=18.17"` | `^1.0.0` | will be published soon |

**Comment by adrai** [comment]
Great 👍

**Comment by kawanet** [comment]
both published 🚀🚀
https://www.npmjs.com/package/rdotjson?activeTab=versions
