### ISSUE TITLE
rdotjson strips text attributes

### ISSUE THREAD

**Issue by pawelkijowskizimperium** [kawanet/rdotjson#2]
I am using rdotjson to extract localization key-value pairs from strings.xml. If strings.xml contains localization items that have text attributes such as `<b><\b>, <u><\u>` etc. those are stripped from the json representation of the localization file. Examples:

```
    <string name="activation_warning">
        <b>Some text:</b> Text.\n\nSome more text.</string>
    <string name="cancel">
        <u>Cancel</u>
    </string>
    <string name="default_latitude" translatable="false">40.7831</string>
    <string name="default_longitude" translatable="false">-73.9712</string>
    <string name="detail_developer_mode_on"><![CDATA[Text. Some more text.]]></string>
    <string name="permission_justification_required_warning">
        <font color="#ff4343">You have declined a required permission. Exiting.</font>
    </string>
```

This is undesired in my case. Are there any options that I can pass into rdotjson in order to preserve text formatting attributes such as `<b></b>,  <u></u>, <![CDATA[  ]]>, <font color="#ff4343"></font>, `new line characters `\n` and any other text attributes?

**Comment by kawanet** [comment]
1.0.0 published with {xml: true, attr: true} options.
