### ISSUE TITLE
optionally parse comments

### ISSUE THREAD

**Issue by kawanet** [kawanet/rdotjson#4]
Thanks to @adrai's PR  #3

> Seems like some android resource files have context information of a specific string resource written next to it as xml comment like this:

```html
<string name="myKey">Hello</string> <!-- the greeting -->
```

```js
rdotjson(xml, {includeComments: true}, function(err, R) {
    console.log(R.string.myKey.comment); // => the greeting
});
```

**Comment by adrai** [comment]
@kawanet do you have some ETA when you will merge the PR and create a new npm version?

**Comment by kawanet** [comment]
@adrai thanks to sending your PR! I've added some tests and features:

- `{includeComments: 'pre'}` option I have some sources which has prepositive comments before each element.
- Use `new String("foo")` object trick instead of plain object `{value: "foo", comment: "bar"}` to get better backward compatibility. Comments are still available via `comment` property like `R.string.app_name.comment`.

Do you think shorter `{comment: true}` option parameter name could work?
The other option parameter names are shorter than `{includeComments: true}`.

**Comment by adrai** [comment]
Wow, sounds great!
The way you like it better ....
The main thing, I come to the comment. ;-)
It may also be called comment: 'pre' and 'post' so always expecting one of these two values...

**Comment by kawanet** [comment]
@adrai was right. I've run it with some of my Android app resources. It seems that closing tag `</string>`'s right-side comment within the same line was best to fetch most relative comment for each item.

```xml
<string name="myKey">Hello</string> <!-- the greeting -->
```

I've then added the third option `{comment: 'right'}` which works similar to your first PR.
It ignores following comments located after a newline character.

**Comment by adrai** [comment]
LGTM

**Comment by adrai** [comment]
You are awesome! Thanks a lot.

**Comment by kawanet** [comment]
1.0.0 published with `{comment: '(pre|post|right)'}` option.
CSV/Swift formatter also supports the comment property.

```sh
# CSV
./node_modules/.bin/rdotjson --comment=right --format=csv --output=strings.csv app/src/main/res/values/strings.xml
# Swift
./node_modules/.bin/rdotswift --comment=right --output=R.swift app/src/main/res/values/strings.xml
```

My personal main purpose of `rdotjson` is to generate files of `.csv` for planners and `.swift` for iOS app developer as above. XML comments must help them as well. Thanks!
